# Question 61281645

**Description: [_Getting a KeyError when trying to run De-dupe_][#Q]**

[Source][#Q]

[#Q]: https://stackoverflow.com/questions/61281645/getting-a-keyerror-when-trying-to-run-de-dupe

## Keywords

```bash
# comma separated list of keywords
python, pandas, python-dedupe
```

---

# Solution

Swap the following line:

```python
#Running De-Dupe for state Ohio ('oh')
dp.dedupe_dataframe(state_data['oh'], ['StoreBannerName','Address','City','State'])
```

**WITH**

```python
#Running De-Dupe for state Ohio ('oh')
state_data['oh'].dedupe_dataframe(subset = ['StoreBannerName','Address','City','State'], keep='first')
```

### Reference

+ [`pandas.DataFrame.drop_duplicates()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html)

---
